<!-- Presents a list of topics and details on the currently visible topic. -->
<script lang='ts'>
	import { gesture } from '$lib/cross-platform'
	import type { GestureCallback } from '$lib/cross-platform'
	import type { Topic } from '$lib/state'
	import { tweened } from 'svelte/motion'
	import { clamp } from '$lib/utils'
	import { quintOut } from 'svelte/easing'
	import { Spacer } from '@ollopa/cedar'

	export let topics: Topic[]

	const offset = tweened(0, { easing: quintOut })
	const velocityThreshold = 3
	const panThreshold = 200

	let width: number
	let topicsArea: HTMLElement
	let offsetStart = 0

	const handleMoveStart = _ => {
		offsetStart = $offset
	}

	const handleMove: GestureCallback = (e) => {
		// The +10/-10 gives a rubber banding effect similar to iOS
		$offset = clamp($offset + e.deltaX, -(width / 2) - 10, 10)
	}

	const handleMoveEnd: GestureCallback = e => {
		// Only change the view if it was a big swipe
		if (e.velocityX < -velocityThreshold || e.deltaX < -panThreshold) {
			$offset = -(width / 2)
		} else if (e.velocityX > velocityThreshold || e.deltaX > panThreshold) {
			$offset = 0
		} else {
			$offset = offsetStart
		}
	}
</script>

<div 
	class='topics-area' 
	use:gesture={{ onMove: handleMove, onEnd: handleMoveEnd, onStart: handleMoveStart, threshold: 15 }} 
	bind:this={topicsArea}
	bind:clientWidth={width}
	style='transform: translateX({$offset}px);'
>
	<div class='topics' >
		{#each topics as { name, description, imageUrl }}
			<div class='topic'>
				<img src={imageUrl} alt={name}>
				<div class='details'>
					<h3>{name}</h3>
					<p>{description}</p>
				</div>
			</div>
		{/each}
	</div>

	<div class='topic-info'>
		<h1>Big Cats</h1>

		<Spacer s={4} />

		<p>
			Today on Vizz, we will tell you about Big Cats!
		</p>

		<!-- Everything below was generated by a GPT-2 flavor language model. Don't judge. -->

		<p>
			To start, we have had a new character named Bongo, named Bongo Pappy! I don't know if I can explain it well enough but on this Vizz Show, you will have these two characters called Big Cats, and Bongo Pappy. So what are we looking for in an episode? If Big Cats were to have their own character you would need to just choose one that would best suit your story. I mean Bongo Pappy! You might be thinking, "Well, I can't get a Big Cat as the Big Cat." Well, now they are so different! So this one is for you, and for us as creators.
		</p>

		<p>
			I am on the podcast today and I want to share with you just one thing we will look at.
		</p>

		<p>
			Big Cats – Big Cats is a new episode. This is a special episode called Big Cats.
		</p>

		<p>
			And we also have some big cats all over the world. The episode of Big Cats is about the Big Cats of Canada, but that is not what Big Cats is about. I think it is very similar as it is a story about the Big Cats and about Bongo Pappy. But we will also talk about how Bongo Pappy is a lot more of this story and the story about Big Cats.
		</p>
	</div>
</div>

<style>
	.topics-area {
		display: grid; 
		grid-template-columns: 1fr 1fr;
		grid-template-areas: 'topics topic-info'; 
		padding: var(--s-4);
	}

	.topics {
		grid-area: topics;
		display: grid;
		row-gap: var(--s-8);
	}

	.topic {
		display: grid;
		grid-template-columns: 2fr 3fr;
		column-gap: var(--s-6);
	}
	.topic img {
		object-fit: cover;
		width: 100%;
		height: 100%;
		border-radius: var(--borderRadiusSmall);
		box-shadow: var(--shadow-1);
	}
	.topic .details {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: flex-start;
		color: var(--white);
		max-width: 20rem;
	}
	.topic .details p {
		margin-top: var(--s-4);
	}

	.topic-info {
		background: var(--lightGray);
		border-radius: var(--borderRadiusSmall);
		box-shadow: var(--shadow-1);
		padding: var(--s-4) var(--s-8);
	}
	.topic-info p {
		margin-bottom: var(--s-4);
	}
</style>